from repo

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,15 +1,82 @@
 name: Release
+run-name: "${{ format('{0} [{1}]', inputs.release_version, github.ref_name) }}"
+
+concurrency:
+  cancel-in-progress: true
+  group: release
 
 on:
-  release:
-    types: [published]
+  workflow_dispatch:
+    inputs:
+      release_version:
+        description: Version (e.g. 1.2.3)
+        required: true
+        type: string
 
 jobs:
 
+  Version:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Validate input
+        id: validate-input
+        env:
+          INPUT_VERSION: "${{ inputs.release_version }}"
+        run: |
+          set -euxo pipefail
+          if [[ ! "$INPUT_VERSION" =~ ^v?([0-9]+)[.]([0-9]+)[.]([0-9]+)$ ]]; then
+            echo "::error::Invalid version: $INPUT_VERSION"
+            exit 1
+          fi
+          awk -v MAJOR="${BASH_REMATCH[1]}" -v MINOR="${BASH_REMATCH[2]}" -v PATCH="${BASH_REMATCH[3]}" '
+            BEGIN {
+              printf("VERSION=%d.%d.%d\n", int(MAJOR), int(MINOR), int(PATCH))
+            }
+          ' |tee -a "$GITHUB_OUTPUT" |tee -a "$GITHUB_ENV"
+      - name: Generate title
+        id: generate-title
+        run: |
+          set -euxo pipefail
+          echo "TITLE=v$VERSION [$(date +%Y-%m-%d)]" |tee -a "$GITHUB_OUTPUT"
+      - name: Checkout
+        uses: actions/checkout@v6
+      - name: Validate version
+        run: |
+          set -euxo pipefail
+          old_version="$(grep -Pom1 "VERSION \K[0-9.]+(?=.+Version automatically set by release.yml)" CMakeLists.txt)"
+          if ! dpkg --compare-versions "$INPUT_VERSION" gt "$old_version"; then
+            echo "::error::New version $INPUT_VERSION must be greater than older version $old_version"
+            exit 1
+          fi
+    outputs:
+      TITLE: "${{ steps.generate-title.outputs.TITLE }}"
+      VERSION: "${{ steps.validate-input.outputs.VERSION }}"
+
   Bump:
+    # - Generate new changelog in place and upload as artifact
+    # - Set new version in /CMakeLists.txt
+    # - Commit and push
+    # - Wait for CI to build artifacts (assert)
+    # - Download them and re-upload them here for subsequent job
+    # - Upload redist assets as workflow artifacts
+    needs: Version
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v6
       - name: TODO
         run: echo TODO
+
+  Release:
+    # TODOs:
+    # - Isolate install section from README between anchors into temporary file, upload as workflow artifact
+    # - Download artifacts from workflow
+    # - Create release with all files and body
+    needs: Bump
+    runs-on: ubuntu-latest
+    steps:
+      - name: TODO
+        run: echo TODO
+
+# TODOs:
+# - Revisit CONTRIBUTING.md release instructions.
