Collect

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -15,9 +15,9 @@ on:
 
 jobs:
 
-  Validate:
+  Collect:
     #
-    # Validate and normalize the inputted version, and generate the release datestamp.
+    # Isolate the changelog section and install section into their own files.
     #
     runs-on: ubuntu-latest
     steps:
@@ -27,93 +27,53 @@ jobs:
           INPUT_VERSION: "${{ inputs.release_version }}"
         run: |
           set -euxo pipefail
-          if [[ ! "$INPUT_VERSION" =~ ^v?([0-9]+)[.]([0-9]+)[.]([0-9]+)$ ]]; then
-            echo "::error::Invalid version: $INPUT_VERSION"
+          if [[ ! "$INPUT_VERSION" =~ ^[0-9]+[.][0-9]+[.][0-9]+$ ]]; then
+            echo "::error::Invalid version: $INPUT_VERSION" >&2
             exit 1
           fi
-          awk -v MAJOR="${BASH_REMATCH[1]}" -v MINOR="${BASH_REMATCH[2]}" -v PATCH="${BASH_REMATCH[3]}" '
-            BEGIN {
-              printf("VERSION=%d.%d.%d\n", int(MAJOR), int(MINOR), int(PATCH))
-            }
-          ' |tee -a "$GITHUB_OUTPUT" |tee -a "$GITHUB_ENV"
-      - name: Save date
-        id: save-date
-        run: |
-          set -euxo pipefail
-          date +DATE=%Y-%m-%d |tee -a "$GITHUB_OUTPUT"
       - name: Checkout
         uses: actions/checkout@v6
-      - name: Validate version
-        id: validate-version
+      - name: Get changelog section
         run: |
           set -euxo pipefail
-          old_version="$(grep -Pom1 "VERSION \K[0-9.]+(?=.+Version automatically set by release.yml)" CMakeLists.txt)"
-          if [[ ! "$old_version" =~ ^[0-9]+[.][0-9]+[.][0-9]+$ ]]; then
-            echo "::error::Invalid old_version: $old_version"
+          if ! top_section="$(grep -Pom1 '^## \[[0-9]+[.][0-9]+[.][0-9]+\] - [0-9]{4}-[0-9]{2}-[0-9]{2}$' CHANGELOG.md)"; then
+            echo "::error::Invalid CHANGELOG.md: top section not found" >&2
             exit 1
           fi
-          if ! dpkg --compare-versions "$VERSION" gt "$old_version"; then
-            echo "::error::New version $VERSION must be greater than older version $old_version"
+          if ! echo "$top_section" |grep -P "(?<=[)$INPUT_VERSION(?=])"; then
+            echo "::error::Version mismatch (cl): '$INPUT_VERSION' not in '$top_section'" >&2
             exit 1
           fi
-          echo "OLD_VERSION=$old_version" |tee -a "$GITHUB_OUTPUT"
-    outputs:
-      DATE: "${{ steps.save-date.outputs.DATE }}"
-      NEW_VERSION: "${{ steps.validate-input.outputs.VERSION }}"
-      OLD_VERSION: "${{ steps.validate-version.outputs.OLD_VERSION }}"
-
-  Changelog:
-    #
-    # Generate the changelog for the release.
-    #
-    needs: Validate
-    runs-on: ubuntu-latest
-    env:
-      DATE: "${{ needs.Validate.outputs.DATE }}"
-      NEW_VERSION: "${{ needs.Validate.outputs.NEW_VERSION }}"
-      OLD_VERSION: "${{ needs.Validate.outputs.OLD_VERSION }}"
-    steps:
-      - name: Validate
+          echo TODO cl_section.md
+      - name: Verify version in CMakeLists.txt
         run: |
           set -euxo pipefail
-          test -n DATE
-          test -n NEW_VERSION
-          test -n OLD_VERSION
-      - name: Checkout
-        uses: actions/checkout@v6
-        with:
-          fetch-depth: 0  # for git log
-      - name: TODO
+          if ! project_line="$(grep -Pm1 '^\s*project\(.+ VERSION [0-9.]+(?=[^0-9.])' CMakeLists.txt)"; then
+            echo "::error::Invalid CMakeLists.txt: project line not found" >&2
+            exit 1
+          fi
+          if ! echo "$project_line" |grep -P "(?<=VERSION )$INPUT_VERSION(?=[^0-9.])"; then
+            echo "::error::Version mismatch (cm): '$INPUT_VERSION' not in '$project_line'" >&2
+            exit 1
+          fi
+      - name: Get install section
         run: |
           set -euxo pipefail
-          printenv DATE
-          printenv NEW_VERSION
-          printenv OLD_VERSION
-
-  Bump:
-    # - Prepend new changelog section to CHANGELOG.md
-    # - Set new version in /CMakeLists.txt
-    # - Commit changes to both files and push
-    # - Wait for CI to build artifacts
-    # - Download release artifacts (2 files) and re-upload them here for subsequent job
-    # - Upload redist assets (2 files) as workflow artifacts
-    needs: [Validate, Changelog]
-    runs-on: ubuntu-latest
-    env:
-      DATE: "${{ needs.Validate.outputs.DATE }}"
-      NEW_VERSION: "${{ needs.Validate.outputs.NEW_VERSION }}"
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v6
-      - name: TODO
-        run: echo TODO
+          echo TODO install.md
+      - name: Get release artifacts
+        run: |
+          set -euxo pipefail
+          echo TODO download-artifact commit sha
+      - name: Upload artifacts
+        run: |
+          set -euxo pipefail
+          echo TODO upload cl_section.md, install.md, skprx, suprx, redist/suprx, redist/rco
 
   Release:
     # TODOs:
-    # - Isolate install section from README between anchors into temporary file, upload as workflow artifact
-    # - Download the four artifacts from workflow
+    # - Download the four+2 artifacts from workflow
     # - Create release with all files and body
-    needs: Bump
+    needs: Collect
     runs-on: ubuntu-latest
     steps:
       - name: TODO
