from repo

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -15,7 +15,7 @@ on:
 
 jobs:
 
-  Version:
+  Validate:
     runs-on: ubuntu-latest
     steps:
       - name: Validate input
@@ -44,8 +44,8 @@ jobs:
         run: |
           set -euxo pipefail
           old_version="$(grep -Pom1 "VERSION \K[0-9.]+(?=.+Version automatically set by release.yml)" CMakeLists.txt)"
-          if ! dpkg --compare-versions "$INPUT_VERSION" gt "$old_version"; then
-            echo "::error::New version $INPUT_VERSION must be greater than older version $old_version"
+          if ! dpkg --compare-versions "$VERSION" gt "$old_version"; then
+            echo "::error::New version $VERSION must be greater than older version $old_version"
             exit 1
           fi
     outputs:
@@ -59,7 +59,7 @@ jobs:
     # - Wait for CI to build artifacts (assert)
     # - Download them and re-upload them here for subsequent job
     # - Upload redist assets as workflow artifacts
-    needs: Version
+    needs: Validate
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
